version: '3.8'

services:
  production:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    command: npm run dev